let animalredbook = [
    {
        Tên:'Chồn dơi',
        Họ:'Chồn dơi',
        Bộ:'Cánh da',
        Đặcđiểmnhậndạng:'Đầu rộng, tai ngắn tròn hoặc tù. Mắt to, màu nâu đỏ hay nâu lục nhạt. Màng da nối từ cổ với chi trước, chi sau tới hết các ngón chân và bao phủ đầu mút đuôi. Lông trên lưng và mặt mang da màu xám tro với nhiều lốm đốm màu trắng nhạt. Lông bụng và mặt dưới màng da hung đỏ hoặc nhạt hơn, không có đốm. Con cái có màu xám, con đực màu sáng hơn chuyển dần sang màu nâu, thậm chí hơi đỏ. Chiều dài chi trước và chi sau gần bằng nhau, có 5 ngón. Các ngón chân nối nhau bằng màng da tới tận vuốt chân. Đuôi dài khoảng 1/3 thân.',
        Sinhhọcsinhthái:'Chồn dơi sống đơn lẻ trong các khu rừng nguyên sinh hay thứ sinh có nhiều cây gỗ to trên núi cao và vùng đất thấp. Chồn dơi hoàn toàn sống trên cây. Chúng bò trên cây giỏi nhưng chậm, có thể bay lượn từ cây này qua cây khác với khoảng cách khá xa. Hoạt dộng vào ban đêm. Thức ăn là quả cây rừng, trứng chim và chim non. Chồn dơi nuôi con trong chuồng bằng các loại quả mềm và các loại rau xanh như: chuối, đu đủ, cam , xoài, rau diếp... Làm tổ trong bọng cây to cao 20-50m. Mùa sinh sản từ 6 đến 9 tháng. Mang thai khoảng 8 tuần. Đẻ mỗi lứa 1 con. Con sơ sinh yếu được nuôi trong túi do màng da ở phần đuôi tạo thành. Túi da mềm và ấm, con non sống trong túi đến khi tự lập. Con non chưa cai sữa mẹ, mẹ đã chửa lứa tiếp theo.',
        Phânbố:'Trong nước: Lai Châu, Thanh Hóa, Nghệ An, Hà Tĩnh, Quảng Bình, THừa THiên - Huế, Kon Tum, Gia Lai, Đăk Lawk, Tây Ninh. Thế giới: Ấn Độ, Thái Lan, Malaixia, Inđônexia, Lào, Campuchia.',
        Giátrị:'Loài thú quý, hiếm, đã được đưa vào Sách Đỏ Thế giới.',
        Tìnhtrạng:'Độ suy giảm quần thể ít nhất 50% trong 10 năm gần đây do chặt phá rừng làm mất nới cư trú của chúng. Nới cư trú suy giảm nghiêm trọng. Diện tích phân bố hiện nay ước tính dưới 20000km^2, nơi cư trú giảm từ 2000km^2 xuống dưới 500^2.',
        Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam(1992-2000). Cấm tuyệt đối săn bắn. Xây dựng các khu bảo tồn có Chồn Dơi.  TÌm cách nuôi, nhân giống trong vườn thú.',   
    },
    {
        Tên:'Dơi chó tai ngắn',
        Họ:'Dơi quả',
        Bộ:'Dơi',
        Đặcđiểmnhậndạng:'Tai ngắn,có viền trắng hoặc xám, chiều dài nhỏ hơn 18mm. Bộ lông màu xám nhạt hay nâu. Lông ở vùng vai, cổ và hông của con trưởng thành có màu da cam hoặc vàng tươi.',
        Sinhhọcsinhthái:'Dơi chó tai ngắn thường sống ở nhiều kiểu sinh cảnh khác nhau: từ rừng núi đến đồng bằng, các khu đô thị..; trú ngụ dưới mái của các công ty xây dựng, vách hang và dưới tán cây, loài dơi này có thể bay khoảng 97-113 km trong môi trường đêm để kiếm ăn. Thức ăn của chúng là mật hoa, quả, hạt của nhiều loài khác nhau. Con cái có thời kì mang thai từ tháng 12 năm trước đến tháng 8 năm sau; thời gian mang thai từ 115 đến 125 ngày; có 2 thời kì sinh con non trong mỗi năm (từ tháng 2 đến tháng 3 và từ tháng 6 đến tháng 8), trong mỗi năm, thời gian mang thai lần thứ 2 trùng vói thời gian tiết sữa lần thứ nhất. Khi mới sinh, con non nặng khoảng 11g; được mẹ mang theo 45 đến 50 ngày; cai sữa khi được khoảng 40 đến 45 ngày. Con cái thành thục sinh dục ở khoảng 5 đến 6 tháng tuổi; con đực thành thục sinh dục ở khoảng 15-20 tháng tuổi',
        Phânbố:'Trong nước: Lào Cai, Hòa Bình, Hải Dương, Hà Nội, Ninh Bình, Quảng Trị, Thùa Thiên-Huế, Quảng Nam, Kháng Hòa, Kon Tum, Đăk Lawk, lâm Đồng, Ninh Thuận, Đồng Nai, Thành phố Hồ Chí Minh, Tây Ninh, Kiên Giang. Thế giới: Ấn Độ, Nepan, Trung Quốc, Thái Lan, Indôneeexxia, Malaisia và Philipin,',
        Giátrị:'Có vai trò quan trọng trong phát tán thực vật. Phân loài C.b.hoffeti là đặc hữu của miền Bắc Việt Nam.',
        Tìnhtrạng:'Phân bố rộng. Loài dơi đã và đang là đối tượng săn bắt của dân địa phương ở nhiều khu vực nên hiện trạng của chúng đang bị suy giảm nghiêm trọng về số lượng và phạm vi phân bố. Riêng loại C.b.hoffeti rất hiếm và không ghi nhận được trong thời gian từ năm 1994 đến nay.',
        Biệnphápbảovệ:'Đã được đưa vào sách đỏ Việt Nam năm 2000. Cần ngăn chặn các hoạt động săn bắt và các tác động có hại với loài này ở các khu vực đã được ghi nhận.',
    },
    {
        Tên:'Dơi lá quạt',
        Họ:'Dơi lá mũi',
        Bộ:'Dơi',
        Đắcđiểmnhậndạng:'Lông mặt lưng màu nâu sẫm, phần ngọn sơi lông màu nhạt hơn phần thân và phần gốc. Lông mặt bụng màu xám khói. Cằm và ngực màu xám nhạt. Loa tai to và có dạng hình phễu. Mấu tai cao, hẹp, có các cạnh gần như song song với nhau và đỉnh uốn tròn. Thùy liên kết thấp và kém phát triển. ',
        SinhhọcSinhthái:'Dơi lá quạt thường sông theo đàn, trú ngụ dưới tán cây, hang dộng, khe đá...; kiếm ăn bằng cách bắt côn trung xung quanh các cây to, bụi rậm, dọc theo lối mòn...',
        Phânbố:'Trong nước: lào Cai, Tuyên Quang, Lạng Sơn, Bắc Kạn, Ninh Bình, Quảng Bình. Thế giới: Đông Bắc Thái Lan.',
        Giátrị:'Là loài dơi hiếm, chỉ được ghi nhận ở Việt Nam và Đông Bắc Thái Lan.',
        Tìnhtrạng:'Phân bố rộng, hiện đang sinh sông ở nhiều khu vực nhưng số lượng rất ít. Kết quả điều tra năm 2001 có ghi nhận được ở Kim Hỷ(tỉnh Bắc kạn).',
        Biệnphápbảovệ:'Đã dược đưa vào sách Đỏ của Việt Nam năm 2000 và Danh lục Đỏ của IUCN năm 2000. Cần ngăn chặn hiện tượng săn bắt dơi trong hệ thống hang động ở Kim Hỷ và các khu vực khác có ghi nhận về loài dơi này.',
    },
    {
        Tên:'Dơi lá Tôma',
        Họ:'Dơi lá mũi',
        Bộ:'Dơi',
        Đặcđiểmnhậndạng:'Thùy tam giác rất thấp, rộng và không nhon. Thùy kiên kết khía chữ V. Lá mũi trước nhỏ, hẹp. Bộ lông màu nâu nhạt. Sợi lông có nửa gốc màu vàng nhạt và nửa ngọn màu nâu.',
        SinhhọcSinhthái:'Dơi lá Tooma thương được ghi nhận trong những sinh sản gần sông, suối, ao, hồ...; trú ngụ trong các tán cây, hang, hẻm, các bụi tre, nứa...',
        Phânbố:'Trong nước: Lai Châu, Lào Cai, Bắc kạn, Ninh Bình Thanh Hóa, Nghệ An và Đồng Nai. Thế giới: Mianma, Trung Quốc, Thái Lan.',
        Giátrị:'Diệt muỗi và côn trùng gây hại. ',
        Tìnhtrạng:'Từ năm 1993 đến nay, dơi lá Tooma chỉ được ghi nhận ở một số nơi thuộc miền Bắc và miền Trung, không có ghi nhận ở miền Nam.',
        Biệnphápbảovệ:'Đã được đưa vào danh lục Đỏ của IUCN năm 2000. Cần giảm thiêu săn bắt ở các nơi có ghi nhận loài dơi này.',
    },
    {
        Tên:'Dơi mũi ống cánh lông',
        Họ:'Dơi muỗi',
        Bộ:'Dơi',
        Đặcđiểmnhậndạng:'Mấu tai dài và hơi cong về phía trước. Phầm mõm có lông che phủ(trừ lỗ mũi). Bộ lông dày và mềm. Mặt lưng: ngọn lông màu đỏ tươi, thân lông màu nâu da bò và gốc lông màu xám. Mặt bụng: ngọn lông màu nâu xám, thân và gốc lông sẫm màu hơn. Màng cánh màu hung đỏ che phủ ở mặt trên màng gian đùi, cánh và bàn chân. Lỗ mũi dạng ống.',
        Sinhhọcsinhthái:'Dơi mũi ống cánh lông thường sinh sông trong các sinh cảnh rừng núi, những nơi gần nguồn nước(ao, hồ, sông, suối...), ăn các loại cánh cứng.',
        Phânbố:'Trong nước: Lào Cai, Quảng Bình, Quảng Trị. THế giới: Ấn Độ, Mianma, Trung Quốc, Indônêxia, Philippin.',
        Giátrị:'Là loài dơi hiếm của Việt Nam, có giá trị khoa học',
        Tìnhtrạng:'Phân bố hẹp, số lượng ít. Từ năm 1993 đến nay chỉ có một nơi ghi nhận là Phong Nha-Kẻ Bàng(tỉnh Quảng Bình) với mức độ rất hiếm.',
        Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam năm 2000. Cần ngăn chặn các hoạt dộng săn bát và các tác dộng có hại đối với loài này ở Phong Nha-Kẻ Bàng. Điều tra và xác định hiện trạng của loài ở Lao Bảo để làm cơ sở cho việc xây dựng và thực hiện các biện pháp bảo tồn kịp thời.',
    },
    {
      Tên:'Dơi IO',
      Họ:'Dơi muỗi',
      Bộ:'Dơi',
      Đặcđiểmnhậndạng:'Loài dơi có kích cỡ lớn nhất trong họ dơi muỗi. Màng cánh đồng màu đen. Màng gian đùi đen sẫm ở mặt trên và đen nhạt ở mặt dưới. Đuôi dài và vượt quá màng gian đùi khoảng 6mm. Lông mặt lưng đồng màu nâu xám; lông mặt bụng màu nau xám sẫm. Cạnh trong của loa tai có lông dài che phủ.',
      SinhhọcSinhthái:'Dơi IO thường sinh sông trong các sinh cảnh rừng núi và các loài cây sồi, huyết hụ,... Con cái thường mang thai vào tháng 4, đẻ con từ tháng 5 đến tháng 7. Mỗi năm đẻ một lứa, mỗi lứa đẻ 1 con.',
      Phânbố:'Trong nước: Sơn La, Tuyên Quang, Bắc Kạn, Ninh Bình và Quảng Bình. Thế giới: Ấn Độ, Trung Quốc, Lào, ĐÔng Bắc Thái Lan.',
      Giátrị:'Là loài dơi hiếm của Việt Nam và có giá trị khoa học.',
      Tìnhtrạng:'Phân bố rộng, số lượng ít. Số lượng và phạm vi phân bố của dơi IO đang bị suy giảm nghiêm trọng bởi các hoạt động săn bắt và tàn phá sinh sản sống.',
      Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam năm 2000 và Danh mục Đỏ của UICN năm 2000. Cần ngăn chặn các hoạt động săn bắt và các tác động có hại với loài này ở Kim Hỷ(Bắc Kạn), Na Hang(Tuyên Quang), Cúc Phương(Ninh Bình), Phong Nha - Kẻ Bàng(Quảng Bình).',  
    },
    {
        Tên:'DƠi muỗi chân lớn',
        Họ:'Dơi lá muỗi',
        Bộ:'Dơi',
        Đặcđiểmnhậndạng:'Lông mặt lưng dày và mềm; sợi lông có nửa ngọn màu nâu xám và nửa gốc màu xám sẫm. Màng cánh và màng gian đùi đồng màu nâu sẫm.',
        SinhhọcSinhthái:'Dơi muỗi chân lớn thường sinh sống trong các khu vực rừng núi đá vôi; trú ngụ trong các sinh cảnh gần sông, suối, hồ, ao, đường hầm, khe, hẻm.',
        Phânbố:'Trong nước: Lạng Sơn, Nghệ An và Quảng Bình. THế giới: Trung Quốc(Hồng Kong).',
        Giátrị:'Diệt muỗi và côn trùng gây hại.',
        Tìnhtrạng:'Từ năm 1994 đến nay, chỉ có ghi nhận ở Lang Sơn(Hữu liên), Quảng Bình(Phong Nha - Kẻ Bàng) và Nghệ AN (Pù Mát). Tuy nhiên số lượng cá thể ghi nhận được ở mức rất hiếm.',
        Biệnphápbảovệ:'Đã được đưa vào Danh lục Đỏ của IUCN năm 1996. Cần ngăn chặn hoạt động săn bắt và các tác động có hại đối với đời sông của dơi trong hệ thông hang động ở Hưu Liên, Phong Nha - Kẻ Bàng và Pù Mát.',
    },
    {
        Tên:'Dơi tai sọ cao',
        Họ:'Dơi muỗi',
        Bộ:'DƠi',
        Đặcđiểmnhậndạng:'Lông mặt lưng đồng màu nâu sẫm. Lông mặt bụng có phần ngọn màu nâu nhạt và phần gốc lòng màu nâu sẫm. Màng cánh và màng gian đùi đồng màu nâu. Loa tai dài, có mấu tai hẹp, nhọn và cao khoảng 1/2 chiều cao của loa tai. Ngọn đuôi tự do ngoài màng gian đùi.',
        SinhhọcSinhthái:'Dơi tai sọ cao thường trsu ngụ trong các hang động, đường hầm, khe đá hoặc dưới tán cây; thường bay đi kiếm ăn khi trời mới bắt đầu tối và trở về vào khoảng 30 phút trước khi mặt trời mọc. Loài dơi này thường bay kiếm ăn ở độ cao 2-5m so với mặt đất; có tập tính chao lượn khoảng 10-15 phút ở cạnh nơi trú ngụ trước khi bay đi nơi khác. Thời kì động dụng và mang thai(đối với con cái) từ tháng 6 đến tháng 8 hàng năm.',
        Phânbố:'Trong nước: Lai Châu, Lào Cai, Lạng Sơn, Ninh Bình, Nghệ An, Hà Tĩnh và Kon TUm. Thế giới: Án Độ, Trung Quốc, Thái Lan, Malaixia, Inđônêxia(Borneo).',
        Giátrị:'Là loài dơi hiếm của Việt Nam và có giá trị khoa học. Phân loài M.s.alticratanus là đặc hữu của Việt Nam.',
        Tìnhtrạng:'Phân bố rộng, số lượng ít. Những ghi nhận về loài này ở mức rất hiếm.',
        Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam năm 2000. Cần ngăn chặn các hoạt động săn bắt và các tác động có hại với loài này ở các khu vực đã ghi nhận được.',
    },
    {
        Tên:'Cu li lớn',
        Họ:'Cu li',
        Bộ:'Linh trưởng',
        Đặcđiểmnhậndạng:'Đầu tròn, trên đỉnh đầu có sọc màu nâu sẫm. Mắt trố to. Xung quanh mắt có vòng lông màu nâu đỏ. Từ trên đỉnh đầu có hai sọc nhỏ màu nâu nhạt chạy xuống dưới mắt. Từ hai gốc tai có vệt lông màu nâu nhạt chạt lên đỉnh đầu và liên kết với nhau. Dải lông màu nâu sẫm chạy dọc từ trên đỉnh đầu theo sống lưng xuống phía dưới. Lông mịn màng, có màu vàng đỏ, cũng có thể có màu vàng nhạt hoặc màu xám. Ngực thường có màu xám tro. Bụng màu hơi vàng nhạt. Hông và chân sau có màu đỏ hoe. Kích thước cỡ nhỏ. Dài thân thường nhỏ hơn 380mm. Ngón tay trỏ nhỏ, ngón chân thứ hai có vuốt, các ngón khác có ống. Răng hàm thứ nhất lớn hơn răng hàm thứ hai.',
        SinhhọcSInhthái:'Con đực và con cái trưởng thành sau 21 tháng. Thời gian mang thai 191 ngày. Khoảng thời gian giữa các lần sinh từu 12-18 tháng. Cuộc sông kéo dài khoảng 20 năm. Thúc ăn chủ yếu là quả cây: 50%, các loài động vật: 30% đặc biệt là các loài côn trùng. Hoạt động về ban đêm. Ban nagyf ngủ trên cây cuộn tròn, mặt cúi vào trong lòng. Chúng thường làm tổ trên các hốc cây. Cuộc sông leo trèo. Sông đơn độc hoặc thành nhóm 3-4 cá thể. Khu vực sống chủ yếu là rừng tre nứa, rừng nguyên sinh, cây bụi, các khu vườn thứ sinh. CHúng thích các vị trí trên đỉnh núi hoặc đỉnh giông có thể cao tới 1300m so với mực nước biển.',
        Phânbố:'Trong nước: Yên Bái(Ta Lang), Tuyên QUang(Bản Bung, Tát Kẻ), Bắc Kạn(Đình Cả, Bản Thi, Ba Bể, Chợ Rãi), Lạng Sơn(Hoa THong_, Bắc Ninh(Thăng long), Hòa Bình(Đà Bắc), Quảng Trị(Lao Bảo), Thừa Thiên - Huế(Bạch Mã), Gia Lai(Kon Cha Răng), Kon TUm(Sa Thầy, Mom Ray). Thế giới: Bawngladet, Mianma, Trung Quốc, Lào, Campuchia, Thái Lan, Malaixia, Inđônêxia.',
        Giátrị:'Làm thuốc, nuôi suất khẩu.',
        Tìnhtrạng:'Trước năm 1975, loài này còn rất phổ biến ử các khu rừng từ các tỉnh phía Bắc tới Gia Lai, Kon Tum trên diện tích >200000km^2. Từ năm 1975 trở lại đây, tình trạng của loài thay đổi rõ rệt. Số lượng quần thể giảm mạnh. Số lượng tiểu quần thể hiện nay còn 30. Nguyên nhân biến đổi: Nới cư trú bị xâm hại, rừng bị chặt phá, diện tích rừng tự nhiên bị thu hẹp và đây là đối tượng săn bắt để nuôi làm cảnh, buôn bán, xuất khẩu.',
        Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam năm 2000 và danh sách các loài cần được bảo vệ của ngành Lâm nghiệp(Phụ lục IB Nghị định 48/2002/NĐ CP ngày 22/4/2002 của Chính phủ). Cần tiến hành tốt việc thực thi các quy chế, nghị định của CHinhs phủ về công tác bảo vệ động vật hoang dã. Xây dựng các khu bảo tồn thiên nhiên và các chương trình quản lí các loài động vật hoang dã nói chung và các loài bị đe dọa nói riêng.',
    },
    {
        Tên:'Cu li nhỏ',
        Họ:'Cu li',
        Bộ:'Linh trưởng',
        Đặcđiểmnhậndạng:'Trông như Cu li lớn nhưng nhỏ hơn và ở lưng màu vàng hơn. Xung quanh hai mắt có vòng tròn lông màu nâu vàng. Có hai dải lông màu nâu xám chạy từ đỉnh đầu xuống trên hai mắt. Từ hai gốc tai có hai vệt rộng màu nâu đỏ chạy từ trên đỉnh dầu và nối với nhau. Lông mềm mại, màu hung nâu xen kẽ ít lông trắng bạc. Dọc sống mũi có vệt trắng. Dọc sông lưng không có sọc hoặc rất mờ, bụng trắng vàng ánh bạc. Răng hàm thứ hai lớn hơn răng hàm thứ nhất. Ngón chân thứ hai có vuốt, các ngón chân khác có vuốt.',
        SinhhọcSinhthái:'Con cái trưởng thành sau 9 tháng, con đực trưởng thành sau 17-20 tháng. Thời gian mang thai kéo dài 188 ngày. Tuổi thọ kéo dài 20 năm. Thức ăn là: quả, nõn cây, côn trùng, trứng chim, chim non trong tổ và chúng thường ăn nhựa cây. Thời gian hoạt động tích cực nhất là vào ban đêm. Thích leo trèo. Loài nay chuyển động nhanh hơn loài Cu li lớn. Sống đơn độc hay thành nhóm nhỏ 3-4 con. Chúng sống trong nhiều sinh cảnh khác nhau. Thích nghi với điều kiện rừng thưa, thoáng, trên các gốc cây, bụi rậm, ven rừng, trên nương rẫy.',
        Phânbố:'Trong nước: Lai CHâu, Sơn La(Sông Mã), Tuyên Quang(CHiêm Hóa, Na Hang), Lạng Sơn, Vĩnh Phúc(Phú Yên), Hà Tây(Ba VÌ), Bắc Giang(Lục Yên), Hà Giang, Hòa Bình, NInh  Bình(Cúc Phương), Thanh Hóa(Hồi Xuân), Nghệ An(Nghĩa Đàn), QUảng Bình(Phong Nha), Thừa Thiên - Huế(Bạch Mã),  Quảng Nam, Đà Nẵng(Sơn Trà), Kon Tum(Sa Thày), Gia Lai(An Khê, Kon Hà Nừng, Kon Cha Răng, Kon Ka Kỉnh), Đăk Lăk(Buôn Mê THuột, Yok Don, Nam Ca, EaSup, EaKat, Đăk Nông), Lâm Đồng(Bảo Lộc), Khánh Hòa(Nha Trang), Đồng Nai(Trắng Bom), Thành phố Hồ Chí Minh. Thế giới: Lào, Campuchia.',
        Giátrị:'Nuôi làm cảnh, xuất khẩu, nghiên cứu khoa học.',
        Tìnhtrạng:'Trước năm 1975: loài này còn gặp rất phổ biến từ các khu rừng từ các tỉnh phía Bắc tới Tràng Bom, Thành phố Hồ Chí Minh với diện tích ước tính khoảng >20000km^2. Từ năm 1975 trở lại đây, tình trạng của loài này thay đổi rõ rệt. Số lượng quần thể giảm mạnh. Số lượng tiểu quần thể hiện nay còn khoảng 30. Nguyên nhân phổ biến có thể là: nơi cư trú bị xâm hại, rừng bị chặt phá, diện tích rừng tự nhiên bị thu hẹp và đây là đối tượng săn bắt để nuôi làm cảnh, buôn bán và xuất khẩu.',
        Biệnphápbảovệ:'Đã được đưa vào sách Đỏ Việt Nam năm 2000 và danh sách các laoif cần được bảo vệ của ngành Lâm nghiệp(Phụ lục IB Nghị định 48/2002/NĐ CP ngày 22/4/2002 của Chính Phủ). Cần tiến hành tốt việc thực thi pháp luật, các quy chế, nghị định của chính phủ về công tác bảo vệ động vật hoang dã. Xây dựng các khu bảo tồn thiên nhiên và các chương trình quản lí các dộng vật hoang dã nói chung và các loài bị đe dọa nói riêng.', 
    },
];

// {
//     thu : [],
//     chim: [],
//     bosat_luoncu: [],
//     ca: [],
//     dongvat_khongxuongsong: []
// }

